import type { CatalogSnapshot, CatalogSystem } from "./types";

export const BUNDLED_CATALOG_VERSION = "bundled-2026-09-02";

const DEFAULT_CAPABILITIES = {
  docked: true,
  dockless: false,
  ebike: true,
  station_status: true,
} as const;

export const BUNDLED_CATALOG_SYSTEMS: readonly CatalogSystem[] = [
  {
    system_id: "lyft_nyc",
    source_system_id: "lyft_nyc",
    name: "Citi Bike",
    operator: "Lyft",
    city: "New York City",
    region: "New York",
    country_code: "US",
    timezone: "America/New_York",
    discovery_url: "https://gbfs.citibikenyc.com/gbfs/2.3/gbfs.json",
    detected_version: "2.3",
    languages: ["en"],
    license: {
      id: null,
      name: "Citi Bike Data Use Policy",
      url: "https://citibikenyc.com/data-sharing-policy",
      status: "declared",
    },
    capabilities: DEFAULT_CAPABILITIES,
    coverage: {
      bounds: { south: 40.49, west: -74.27, north: 40.92, east: -73.68 },
      centroid: { latitude: 40.7128, longitude: -74.006 },
      confidence: "catalog_metadata",
      buffer_meters: 5_000,
    },
    location_hint: "enam",
    reviewed_hosts: ["gbfs.citibikenyc.com", "gbfs.lyft.com"],
    request_headers: {},
    preferred_languages: ["en"],
    enabled: true,
  },
  {
    system_id: "mobibikes_ca_vancouver",
    source_system_id: "Mobibikes_CA_Vancouver",
    name: "Mobi by Rogers (Vancouver)",
    operator: "Vancouver Bike Share",
    city: "Vancouver",
    region: "British Columbia",
    country_code: "CA",
    timezone: "America/Vancouver",
    discovery_url:
      "https://gbfs.kappa.fifteen.eu/gbfs/2.2/mobi/en/gbfs.json",
    detected_version: "2.2",
    languages: ["en"],
    license: {
      id: "ODbL-1.0",
      name: "Open Data Commons Open Database License 1.0",
      url: "https://spdx.org/licenses/ODbL-1.0.html",
      status: "declared",
    },
    capabilities: DEFAULT_CAPABILITIES,
    coverage: {
      bounds: { south: 49.2, west: -123.3, north: 49.32, east: -123.02 },
      centroid: { latitude: 49.2827, longitude: -123.1207 },
      confidence: "catalog_metadata",
      buffer_meters: 5_000,
    },
    location_hint: "wnam",
    reviewed_hosts: ["gbfs.kappa.fifteen.eu"],
    request_headers: {},
    preferred_languages: ["en"],
    enabled: true,
  },
  {
    system_id: "oslobysykkel",
    source_system_id: "oslobysykkel",
    name: "Oslo Bysykkel",
    operator: "UIP Bauer Media Outdoor Norge AS",
    city: "Oslo",
    region: "Oslo",
    country_code: "NO",
    timezone: "Europe/Oslo",
    discovery_url:
      "https://api.entur.io/mobility/v2/gbfs/v3/oslobysykkel/gbfs",
    detected_version: "3.0",
    languages: ["nb"],
    license: {
      id: "NLOD-2.0",
      name: "Norwegian Licence for Open Government Data 2.0",
      url: "https://data.norge.no/nlod/en/2.0",
      status: "declared",
    },
    capabilities: DEFAULT_CAPABILITIES,
    coverage: {
      bounds: { south: 59.84, west: 10.58, north: 60.02, east: 10.95 },
      centroid: { latitude: 59.9139, longitude: 10.7522 },
      confidence: "catalog_metadata",
      buffer_meters: 5_000,
    },
    location_hint: "weur",
    reviewed_hosts: ["api.entur.io"],
    request_headers: { "ET-Client-Name": "openbike-mcp" },
    preferred_languages: ["nb", "en"],
    enabled: true,
  },
  {
    system_id: "nextbike_wr",
    source_system_id: "nextbike_wr",
    name: "WienMobil Rad",
    operator: "nextbike GmbH",
    city: "Vienna",
    region: "Vienna",
    country_code: "AT",
    timezone: "Europe/Berlin",
    discovery_url:
      "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_wr/gbfs.json",
    detected_version: "2.3",
    languages: ["de", "en"],
    license: {
      id: "CC0-1.0",
      name: "Creative Commons Zero v1.0 Universal",
      url: "https://spdx.org/licenses/CC0-1.0.html",
      status: "declared",
    },
    capabilities: DEFAULT_CAPABILITIES,
    coverage: {
      bounds: { south: 48.1, west: 16.18, north: 48.32, east: 16.58 },
      centroid: { latitude: 48.2082, longitude: 16.3738 },
      confidence: "catalog_metadata",
      buffer_meters: 5_000,
    },
    location_hint: "weur",
    reviewed_hosts: ["gbfs.nextbike.net"],
    request_headers: {},
    preferred_languages: ["de", "en"],
    enabled: true,
  },
];

export const BUNDLED_CATALOG: CatalogSnapshot = {
  schema_version: 1,
  version: BUNDLED_CATALOG_VERSION,
  generated_at: "2026-09-02T00:00:00.000Z",
  source_url:
    "https://raw.githubusercontent.com/MobilityData/gbfs/master/systems.csv",
  source_etag: null,
  systems: [...BUNDLED_CATALOG_SYSTEMS],
};
